### ISSUE TITLE
Remove Spaces in Birthday

### ISSUE THREAD

**Issue by Kyle-Pu** [Kyle-P/Birthday-Reminder#10]
The line of code `contactInfo[1].replaceAll(" ", ""); ` does not work. It fails to remove spaces from the birthday. Please find out how to remove spaces from the birthday. Thanks!

**Comment by perdomoff** [comment]
Kyle,

   Try contactInfo[1].replaceAll("\\s+","");
  It  removes  whitespaces, non-visible characters like tab and \n.

Thanks,
Freddy

**Comment by Kyle-Pu** [comment]
Thanks @perdomoff! That's a great idea. I'll change it to remove all whitespace. However, I did also find that the problem was I actually need to set it like this: `contactInfo[1] = contactInfo[1].replaceAll("\\s", "");` in order for the changes to take place.

Thanks again!

**Comment by perdomoff** [comment]
Of course without that, the edited string would not be saved but even then, searching on just 1 space leaves you open to missing scenarios.
